# Generated by Django 4.2 on 2026-09-01 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome_razao_social', models.CharField(max_length=150, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Preenchido apenas para Pessoa Jurídica.', max_length=150, null=True)),
                ('cpf_cnpj', models.CharField(help_text='Somente números. 11 dígitos (CPF) ou 14 (CNPJ).', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('rg_ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / Inscrição Estadual')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_principal', models.CharField(help_text='Somente números, com DDD. Ex: 31999998888', max_length=15, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('telefone_secundario', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('cep', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Soft delete: marcar como False em vez de excluir o registro.')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('nome_razao_social', models.CharField(max_length=150, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Preenchido apenas para Pessoa Jurídica.', max_length=150, null=True)),
                ('cpf_cnpj', models.CharField(help_text='Somente números. 11 dígitos (CPF) ou 14 (CNPJ).', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_principal', models.CharField(help_text='Somente números, com DDD. Ex: 31999998888', max_length=15, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('telefone_secundario', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('cep', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas dígitos numéricos.', regex='^\\d+$')])),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Soft delete: marcar como False em vez de excluir o registro.')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedor',
                'ordering': ['nome_razao_social'],
            },
        ),
    ]
