# Generated by Django 4.2 on 2026-09-02 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Use o formato ABC1234 ou ABC1D23 (Mercosul).', regex='^[A-Z]{3}\\d[A-Z0-9]\\d{2}$')])),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=80)),
                ('ano_fabricacao', models.PositiveSmallIntegerField()),
                ('ano_modelo', models.PositiveSmallIntegerField()),
                ('cor', models.CharField(blank=True, max_length=40, null=True)),
                ('km', models.PositiveIntegerField(default=0, verbose_name='Quilometragem')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='backend.cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('quantidade_minima', models.PositiveIntegerField(default=0, help_text='Abaixo desta quantidade, o produto entra nos alertas de estoque baixo.')),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='backend.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando_peca', 'Aguardando peça'), ('concluida', 'Concluída'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('mecanico_responsavel', models.CharField(max_length=100)),
                ('data_abertura', models.DateField()),
                ('data_previsao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='backend.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='backend.veiculo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'ordem_servico',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receber', 'A receber'), ('pagar', 'A pagar')], max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='backend.ordemservico')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'db_table': 'lancamento',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('peca', 'Peça')], max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='backend.ordemservico')),
            ],
            options={
                'verbose_name': 'Item de OS',
                'verbose_name_plural': 'Itens de OS',
                'db_table': 'item_os',
            },
        ),
    ]
